[package]
name = "moonbrain-gd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.2.1"
lazy_static = "1.5.0"
rayon = "1.10.0"
ron = "0.8.1"
serde = "1.0.216"
thiserror = "2.0.6"

[lints.clippy]
all = "warn"
pedantic = "warn"
